 drop database notas_enfermeria;

-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 00:08:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notas_enfermeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notas_enfermeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notas_enfermeria` DEFAULT CHARACTER SET utf8 ;
USE `notas_enfermeria` ;

-- -----------------------------------------------------
-- Table `notas_enfermeria`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas_enfermeria`.`persona` (
  `cedula` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `fecha_creado` DATE NOT NULL,
  `fecha_modificado` DATETIME NOT NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`cedula`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas_enfermeria`.`signos_vitales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas_enfermeria`.`signos_vitales` (
  `idsignos` INT NOT NULL AUTO_INCREMENT,
  `persona_cedula` VARCHAR(15) NOT NULL,
  `temperatura` VARCHAR(45) NULL,
  `frecuencia_respiratoria` VARCHAR(45) NULL,
  `frecuencia_cardiaca` VARCHAR(45) NULL,
  `presion_arterial` VARCHAR(45) NULL,
  `saturacion_o` VARCHAR(45) NULL,
  `glic` VARCHAR(45) NULL,
  `respons` VARCHAR(45) NULL,
  `turno` VARCHAR(45) NULL,
  `fecha_creado` DATE NOT NULL,
  `fecha_modificado` DATETIME NOT NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idsignos`, `persona_cedula`),
  INDEX `fk_signos_vitales_persona1_idx` (`persona_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_signos_vitales_persona1`
    FOREIGN KEY (`persona_cedula`)
    REFERENCES `notas_enfermeria`.`persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas_enfermeria`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas_enfermeria`.`paciente` (
  `persona_cedula` VARCHAR(15) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `genero` VARCHAR(10) NULL,
  `estado_civil` VARCHAR(15) NULL,
  `escolaridad` SET("ninguna", "primaria completa", "primaria incompleta", "secundaria completa", "secundaria incompleta", "universidad", "tecnica") NULL,
  `habita` VARCHAR(45) NOT NULL,
  `barrera_idiomatica` VARCHAR(45) NULL,
  `domicilio` VARCHAR(100) NOT NULL,
  `religion` VARCHAR(45) NULL,
  PRIMARY KEY (`persona_cedula`),
  CONSTRAINT `fk_paciente_persona1`
    FOREIGN KEY (`persona_cedula`)
    REFERENCES `notas_enfermeria`.`persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas_enfermeria`.`encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas_enfermeria`.`encargado` (
  `persona_cedula` VARCHAR(15) NOT NULL,
  `cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`persona_cedula`),
  INDEX `fk_encargado_persona1_idx` (`persona_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_encargado_persona1`
    FOREIGN KEY (`persona_cedula`)
    REFERENCES `notas_enfermeria`.`persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas_enfermeria`.`usuario_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas_enfermeria`.`usuario_sistema` (
  `idusuario_sistema` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(10) NOT NULL,
  `encargado_id_encargado` INT NOT NULL,
  `encargado_persona_cedula` VARCHAR(15) NULL,
  `fecha_creado` DATE NOT NULL,
  PRIMARY KEY (`idusuario_sistema`),
  INDEX `fk_usuario_sistema_encargado1_idx` (`encargado_persona_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_sistema_encargado1`
    FOREIGN KEY (`encargado_persona_cedula`)
    REFERENCES `notas_enfermeria`.`encargado` (`persona_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas_enfermeria`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas_enfermeria`.`notas` (
  `idnotas` INT NOT NULL AUTO_INCREMENT,
  `paciente_persona_cedula` VARCHAR(15) NOT NULL,
  `encargado_id_encargado` INT NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `fecha_creado` DATE NOT NULL,
  `fecha_modificado` DATETIME NOT NULL,
  `nota` TEXT NOT NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idnotas`, `paciente_persona_cedula`),
  INDEX `fk_notas_paciente1_idx` (`paciente_persona_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_notas_paciente1`
    FOREIGN KEY (`paciente_persona_cedula`)
    REFERENCES `notas_enfermeria`.`paciente` (`persona_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
